-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."MyDimDate"
(
    dateid integer NOT NULL,
    day integer NOT NULL,
    weekday integer,
    weekdayname character varying(10),
    month integer NOT NULL,
    monthname character varying(10),
    quarter integer,
    quartername character varying(2),
    year integer NOT NULL,
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."MyDimWaste"
(
    wasteid integer NOT NULL,
    waste_type character varying(50),
    PRIMARY KEY (wasteid)
);

CREATE TABLE IF NOT EXISTS public."MyDimZone"
(
    zoneid integer NOT NULL,
    zone character varying(50),
    city character varying(50),
    PRIMARY KEY (zoneid)
);

CREATE TABLE IF NOT EXISTS public."MyFactTrips"
(
    trip_number integer NOT NULL,
    wasteid integer NOT NULL,
    waste_in_tons real,
    zoneid integer NOT NULL,
    dateid integer NOT NULL,
    PRIMARY KEY (trip_number)
);

ALTER TABLE public."MyFactTrips"
    ADD FOREIGN KEY (wasteid)
    REFERENCES public."MyDimWaste" (wasteid)
    NOT VALID;


ALTER TABLE public."MyFactTrips"
    ADD FOREIGN KEY (zoneid)
    REFERENCES public."MyDimZone" (zoneid)
    NOT VALID;


ALTER TABLE public."MyFactTrips"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."MyDimDate" (dateid)
    NOT VALID;

END;