-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."DimDate"
(
    dateid integer NOT NULL,
    date date NOT NULL,
	Year integer NOT NULL,
	Quarter integer,
    QuarterName character varying(2),
	Month integer NOT NULL,
    Monthname character varying(10),
	Day integer,
	Weekday integer,
    WeekdayName character varying(10),
    PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public."DimStation"
(
    Stationid integer NOT NULL,
    City character varying(50),
    PRIMARY KEY (Stationid)
);

CREATE TABLE IF NOT EXISTS public."DimTruck"
(
    Truckid integer NOT NULL,
    TruckType character varying(50),
    PRIMARY KEY (Truckid)
);

CREATE TABLE IF NOT EXISTS public."FactTrips"
(
    Tripid integer NOT NULL,
    Dateid integer NOT NULL,
    Stationid integer NOT NULL,
    Truckid integer NOT NULL,
    Wastecollected real,
    PRIMARY KEY (Tripid)
);

ALTER TABLE public."FactTrips"
    ADD FOREIGN KEY (Dateid)
    REFERENCES public."DimDate" (dateid)
    NOT VALID;


ALTER TABLE public."FactTrips"
    ADD FOREIGN KEY (Stationid)
    REFERENCES public."DimStation" (Stationid)
    NOT VALID;


ALTER TABLE public."FactTrips"
    ADD FOREIGN KEY (Truckid)
    REFERENCES public."DimTruck" (Truckid)
    NOT VALID;

END;